spring.application.name=clases

spring.datasource.url=jdbc:postgresql://localhost:5432/asignaturas
spring.datasource.username=postgres
spring.datasource.password=Tatiana3999
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

server.port=8080
